/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as ApplibraryRouteRouteImport } from './routes/app/(library)/route'
import { Route as AppPlaylistRatingKeyRouteImport } from './routes/app/playlist.$ratingKey'
import { Route as AppArtistRatingKeyRouteImport } from './routes/app/artist.$ratingKey'
import { Route as AppAlbumRatingKeyRouteImport } from './routes/app/album.$ratingKey'
import { Route as ApplibraryTracksRouteImport } from './routes/app/(library)/tracks'
import { Route as ApplibraryArtistsRouteImport } from './routes/app/(library)/artists'
import { Route as ApplibraryAlbumsRouteImport } from './routes/app/(library)/albums'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApplibraryRouteRoute = ApplibraryRouteRouteImport.update({
  id: '/(library)',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlaylistRatingKeyRoute = AppPlaylistRatingKeyRouteImport.update({
  id: '/playlist/$ratingKey',
  path: '/playlist/$ratingKey',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArtistRatingKeyRoute = AppArtistRatingKeyRouteImport.update({
  id: '/artist/$ratingKey',
  path: '/artist/$ratingKey',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlbumRatingKeyRoute = AppAlbumRatingKeyRouteImport.update({
  id: '/album/$ratingKey',
  path: '/album/$ratingKey',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApplibraryTracksRoute = ApplibraryTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => ApplibraryRouteRoute,
} as any)
const ApplibraryArtistsRoute = ApplibraryArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => ApplibraryRouteRoute,
} as any)
const ApplibraryAlbumsRoute = ApplibraryAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => ApplibraryRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof ApplibraryRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/albums': typeof ApplibraryAlbumsRoute
  '/app/artists': typeof ApplibraryArtistsRoute
  '/app/tracks': typeof ApplibraryTracksRoute
  '/app/album/$ratingKey': typeof AppAlbumRatingKeyRoute
  '/app/artist/$ratingKey': typeof AppArtistRatingKeyRoute
  '/app/playlist/$ratingKey': typeof AppPlaylistRatingKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/app': typeof AppIndexRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/albums': typeof ApplibraryAlbumsRoute
  '/app/artists': typeof ApplibraryArtistsRoute
  '/app/tracks': typeof ApplibraryTracksRoute
  '/app/album/$ratingKey': typeof AppAlbumRatingKeyRoute
  '/app/artist/$ratingKey': typeof AppArtistRatingKeyRoute
  '/app/playlist/$ratingKey': typeof AppPlaylistRatingKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/app/(library)': typeof ApplibraryRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/(library)/albums': typeof ApplibraryAlbumsRoute
  '/app/(library)/artists': typeof ApplibraryArtistsRoute
  '/app/(library)/tracks': typeof ApplibraryTracksRoute
  '/app/album/$ratingKey': typeof AppAlbumRatingKeyRoute
  '/app/artist/$ratingKey': typeof AppArtistRatingKeyRoute
  '/app/playlist/$ratingKey': typeof AppPlaylistRatingKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/setup'
    | '/app/settings'
    | '/app/'
    | '/app/albums'
    | '/app/artists'
    | '/app/tracks'
    | '/app/album/$ratingKey'
    | '/app/artist/$ratingKey'
    | '/app/playlist/$ratingKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/app'
    | '/app/settings'
    | '/app/albums'
    | '/app/artists'
    | '/app/tracks'
    | '/app/album/$ratingKey'
    | '/app/artist/$ratingKey'
    | '/app/playlist/$ratingKey'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/setup'
    | '/app/(library)'
    | '/app/settings'
    | '/app/'
    | '/app/(library)/albums'
    | '/app/(library)/artists'
    | '/app/(library)/tracks'
    | '/app/album/$ratingKey'
    | '/app/artist/$ratingKey'
    | '/app/playlist/$ratingKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(library)': {
      id: '/app/(library)'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof ApplibraryRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/playlist/$ratingKey': {
      id: '/app/playlist/$ratingKey'
      path: '/playlist/$ratingKey'
      fullPath: '/app/playlist/$ratingKey'
      preLoaderRoute: typeof AppPlaylistRatingKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/artist/$ratingKey': {
      id: '/app/artist/$ratingKey'
      path: '/artist/$ratingKey'
      fullPath: '/app/artist/$ratingKey'
      preLoaderRoute: typeof AppArtistRatingKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/album/$ratingKey': {
      id: '/app/album/$ratingKey'
      path: '/album/$ratingKey'
      fullPath: '/app/album/$ratingKey'
      preLoaderRoute: typeof AppAlbumRatingKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(library)/tracks': {
      id: '/app/(library)/tracks'
      path: '/tracks'
      fullPath: '/app/tracks'
      preLoaderRoute: typeof ApplibraryTracksRouteImport
      parentRoute: typeof ApplibraryRouteRoute
    }
    '/app/(library)/artists': {
      id: '/app/(library)/artists'
      path: '/artists'
      fullPath: '/app/artists'
      preLoaderRoute: typeof ApplibraryArtistsRouteImport
      parentRoute: typeof ApplibraryRouteRoute
    }
    '/app/(library)/albums': {
      id: '/app/(library)/albums'
      path: '/albums'
      fullPath: '/app/albums'
      preLoaderRoute: typeof ApplibraryAlbumsRouteImport
      parentRoute: typeof ApplibraryRouteRoute
    }
  }
}

interface ApplibraryRouteRouteChildren {
  ApplibraryAlbumsRoute: typeof ApplibraryAlbumsRoute
  ApplibraryArtistsRoute: typeof ApplibraryArtistsRoute
  ApplibraryTracksRoute: typeof ApplibraryTracksRoute
}

const ApplibraryRouteRouteChildren: ApplibraryRouteRouteChildren = {
  ApplibraryAlbumsRoute: ApplibraryAlbumsRoute,
  ApplibraryArtistsRoute: ApplibraryArtistsRoute,
  ApplibraryTracksRoute: ApplibraryTracksRoute,
}

const ApplibraryRouteRouteWithChildren = ApplibraryRouteRoute._addFileChildren(
  ApplibraryRouteRouteChildren,
)

interface AppRouteRouteChildren {
  ApplibraryRouteRoute: typeof ApplibraryRouteRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlbumRatingKeyRoute: typeof AppAlbumRatingKeyRoute
  AppArtistRatingKeyRoute: typeof AppArtistRatingKeyRoute
  AppPlaylistRatingKeyRoute: typeof AppPlaylistRatingKeyRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  ApplibraryRouteRoute: ApplibraryRouteRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlbumRatingKeyRoute: AppAlbumRatingKeyRoute,
  AppArtistRatingKeyRoute: AppArtistRatingKeyRoute,
  AppPlaylistRatingKeyRoute: AppPlaylistRatingKeyRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
