/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServerRouteImport } from './routes/server'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppPlaylistPlaylistIdRouteImport } from './routes/app/playlist.$ratingKey'
import { Route as AppArtistArtistIdRouteImport } from './routes/app/artist.$ratingKey'
import { Route as AppAlbumRatingKeyRouteImport } from './routes/app/album.$ratingKey'

const ServerRoute = ServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlaylistPlaylistIdRoute = AppPlaylistPlaylistIdRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArtistArtistIdRoute = AppArtistArtistIdRouteImport.update({
  id: '/artist/$artistId',
  path: '/artist/$artistId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlbumRatingKeyRoute = AppAlbumRatingKeyRouteImport.update({
  id: '/album/$ratingKey',
  path: '/album/$ratingKey',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/server': typeof ServerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/album/$ratingKey': typeof AppAlbumRatingKeyRoute
  '/app/artist/$artistId': typeof AppArtistArtistIdRoute
  '/app/playlist/$playlistId': typeof AppPlaylistPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/server': typeof ServerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/album/$ratingKey': typeof AppAlbumRatingKeyRoute
  '/app/artist/$artistId': typeof AppArtistArtistIdRoute
  '/app/playlist/$playlistId': typeof AppPlaylistPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/server': typeof ServerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/album/$ratingKey': typeof AppAlbumRatingKeyRoute
  '/app/artist/$artistId': typeof AppArtistArtistIdRoute
  '/app/playlist/$playlistId': typeof AppPlaylistPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/server'
    | '/app/settings'
    | '/app/'
    | '/app/album/$ratingKey'
    | '/app/artist/$artistId'
    | '/app/playlist/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/server'
    | '/app/settings'
    | '/app'
    | '/app/album/$ratingKey'
    | '/app/artist/$artistId'
    | '/app/playlist/$playlistId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/server'
    | '/app/settings'
    | '/app/'
    | '/app/album/$ratingKey'
    | '/app/artist/$artistId'
    | '/app/playlist/$playlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ServerRoute: typeof ServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/playlist/$playlistId': {
      id: '/app/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/app/playlist/$playlistId'
      preLoaderRoute: typeof AppPlaylistPlaylistIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/artist/$artistId': {
      id: '/app/artist/$artistId'
      path: '/artist/$artistId'
      fullPath: '/app/artist/$artistId'
      preLoaderRoute: typeof AppArtistArtistIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/album/$ratingKey': {
      id: '/app/album/$ratingKey'
      path: '/album/$ratingKey'
      fullPath: '/app/album/$ratingKey'
      preLoaderRoute: typeof AppAlbumRatingKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlbumRatingKeyRoute: typeof AppAlbumRatingKeyRoute
  AppArtistArtistIdRoute: typeof AppArtistArtistIdRoute
  AppPlaylistPlaylistIdRoute: typeof AppPlaylistPlaylistIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlbumRatingKeyRoute: AppAlbumRatingKeyRoute,
  AppArtistArtistIdRoute: AppArtistArtistIdRoute,
  AppPlaylistPlaylistIdRoute: AppPlaylistPlaylistIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ServerRoute: ServerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
